### ISSUE TITLE
It's not work on .vue component?

### ISSUE THREAD

**Issue by 3lang3** [MacArthurJustin/vue-remote#1]
//app.js 
Vue.use(VueRemote)

//App.vue
this.$remote 
throw Error: undefined

**Comment by MacArthurJustin** [comment]
@EthanOrange I haven't had any issues using it inside my own components. I'd need to see your structure to see where the issue is occurring.

**Comment by 3lang3** [comment]
@MacArthurJustin 

```
// app.js
import Vue from 'vue'
import App from './components/App.vue'
import store from './store'
import router from './router'
import VueRemote from 'vue-remote'
import './public/styles/main.scss'

Vue.use(VueRemote, {
    secure: false,
    host: 'im.ecpcb.com',
    port: 9501
})

new Vue({
    el: '#app',
    router,
    store,
    render: h => h(App)
})
```


```
// App.vue
import AppHeader from './Header.vue'
import AppFooter from './Footer.vue'

    export default {
        components: {
            AppHeader,
            AppFooter
        },
        created: () => {
            console.log(this.$remote.$on())  // error  this.$remote is undefined
        }
    }
```

**Comment by 3lang3** [comment]
@MacArthurJustin 
Vue version is 2.1.10
if i import Vue again in my componts that Vue.Remote.emit is work, this.$remote but not working still

**Comment by MacArthurJustin** [comment]
@EthanOrange  I think I see the issue Arrow syntax when defining functions keeps the `this` scoped to the outer instance.

try this:

    // App.vue
    import AppHeader from './Header.vue'
    import AppFooter from './Footer.vue'
    export default {
        components: {
            AppHeader,
            AppFooter
        },
        created: function () {
            console.log(this.$remote.$on())  // error  this.$remote is undefined
        }
    }

**Comment by 3lang3** [comment]
@MacArthurJustin omg...   Thank u~   
i think I need more coding by use es6  💃

**Comment by MacArthurJustin** [comment]
@EthanOrange ES6 is nice you just have to make sure your keeping track of your scope. I mainly use arrow syntax for anonymous functions like callbacks or promises.
